(setf tools (list 'hammer 'screwdriver))  ; (hammer screwdriver)
(cons 'pliers tools)                      ; (pliers hammer screwdriver)
tools                                     ; (hammer screwdriver)
(setf tools (cons 'pliers tools))         ; (pliers hammer screwdriver)
tools                                     ; (pliers hammer screwdriver)
(append '(saw wrench) tools)              ; (saw wrench pliers hammer screwdriver)
tools                                     ; (pliers hammer screwdriver)
(setf tools (append '(saw wrench) tools)) ; (saw wrench pliers hammer screwdriver)
tools                                     ; (saw wrench pliers hammer screwdriver)
